{{- if (include "vault-chart.tls.enabled" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-chart.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-chart.server.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- include "vault-chart.gen-certs" . | nindent 2 }}
{{- end }}